# http://module-build.sourceforge.net/META-spec.html
#
name:         Data-Password-Entropy-Old
version:      0.1
version_from: Old.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
